build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs EDITED FOR TEST PURPOSE"
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
